# Generated by Django 5.0.4 on 2025-01-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Account_Number', models.CharField(max_length=20, unique=True)),
                ('ID_Number', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Image_Upload', models.ImageField(blank=True, null=True, upload_to='client_images/')),
                ('Password_Image', models.ImageField(upload_to='password_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Account_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fixed_Account', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Salary_Account', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Savings_Account', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='U_bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Loan_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Loan_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Reason', models.TextField()),
                ('Status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=20)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='U_bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Receipt_Accno', models.CharField(max_length=20)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='U_bank.client')),
            ],
        ),
    ]
