# Generated by Django 5.0.4 on 2025-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='password_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Password_Image',
        ),
        migrations.AddField(
            model_name='client',
            name='Password_Image',
            field=models.ManyToManyField(to='U_bank.passwordimage'),
        ),
    ]
