# Generated by Django 5.0.4 on 2025-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0002_passwordimage_remove_client_password_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordimage',
            name='name',
            field=models.CharField(default='Unnamed Image', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
