# Generated by Django 5.0.4 on 2025-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0003_passwordimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Password_Image',
            field=models.ManyToManyField(blank=True, to='U_bank.passwordimage'),
        ),
        migrations.AlterField(
            model_name='passwordimage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
