# Generated by Django 5.0.4 on 2025-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0005_remove_client_password_image_client_password_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
