# Generated by Django 5.0.4 on 2025-01-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0009_remove_passwordimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordimage',
            name='image',
            field=models.ImageField(default='default', upload_to='password_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordimage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
