# Generated by Django 5.0.4 on 2025-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0010_passwordimage_image_alter_passwordimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Password_Image',
        ),
        migrations.AddField(
            model_name='client',
            name='Password_Image',
            field=models.ImageField(blank=True, null=True, upload_to='password/'),
        ),
    ]
