# Generated by Django 5.0.4 on 2025-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0011_remove_client_password_image_client_password_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Password_Image',
        ),
        migrations.AddField(
            model_name='client',
            name='Password_Image',
            field=models.ManyToManyField(blank=True, to='U_bank.passwordimage'),
        ),
    ]
