# Generated by Django 5.0.4 on 2025-02-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0014_deposithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DEPOSIT', 'Deposit'), ('TRANSACTION', 'Transaction'), ('LOAN_APPROVAL', 'Loan Approval'), ('LOAN_PAYMENT', 'Loan Payment'), ('PROFILE_UPDATE', 'Profile Update')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='U_bank.client')),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
