# Generated by Django 5.0.4 on 2025-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_bank', '0015_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DEPOSIT', 'Deposit'), ('TRANSACTION', 'Transaction'), ('LOAN_PAYMENT', 'Loan Payment'), ('PROFILE_UPDATE', 'Profile Update'), ('LOAN_APPLICATION', 'Loan Application')], max_length=20),
        ),
    ]
